const ApiLibraryEdamam = {
  cusines: [
    "Any",
    "American",
    "Asian",
    "British",
    "Caribbean",
    "Central Europe",
    "Chinese",
    "Eastern Europe",
    "French",
    "Indian",
    "Italian",
    "Japanese",
    "Kosher",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Nordic",
    "South American",
    "South East Asian",
  ],
  mealType: ["Any", "Breakfast", "Dinner", "Lunch", "Snack", "Teatime"],
  health: ["Any", "vegan", "vegetarian", "dairy-free"],
};
export default ApiLibraryEdamam;
